# ------------------------------------------------------------------------------
# Prettier configuration file
# https://prettier.io/docs/configuration.html
# ------------------------------------------------------------------------------

proseWrap: "always"
